#!/bin/bash

set -ouex pipefail

FRELEASE=$(rpm -E %fedora)

# Enable staging for supergfxctl if repo file exists
if [[ -f /etc/yum.repos.d/_copr_ublue-os-staging.repo ]]; then
    sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/_copr_ublue-os-staging.repo
else
    # Otherwise, retrieve the repo file for staging
    curl -Lo /etc/yum.repos.d/_copr_ublue-os-staging.repo https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-"${FRELEASE}"/ublue-os-staging-fedora-"${FRELEASE}".repo
fi

if [[ "${BASE_IMAGE_NAME}" == "kinoite" ]]; then
    VARIANT_PKGS="supergfxctl-plasmoid supergfxctl"
elif [[ "${BASE_IMAGE_NAME}" == "silverblue" ]]; then
    VARIANT_PKGS="gnome-shell-extension-supergfxctl-gex supergfxctl"
else
    VARIANT_PKGS=""
fi

# Install NVIDIA driver RPMs using rpm directly to bypass dnf5/rpm6 digest issues
rpm -Uvh --nodeps --nodigest --replacepkgs \
    /rpms/nvidia/libnvidia-cfg-*.rpm \
    /rpms/nvidia/libnvidia-fbc-*.rpm \
    /rpms/nvidia/libnvidia-gpucomp-*.rpm \
    /rpms/nvidia/libnvidia-ml-*.rpm \
    /rpms/nvidia/nvidia-libXNVCtrl-5*.rpm \
    /rpms/nvidia/nvidia-settings-5*.rpm \
    /rpms/nvidia/nvidia-driver-*.rpm \
    /rpms/nvidia/nvidia-kmod-common-*.rpm \
    /rpms/nvidia/nvidia-modprobe-5*.rpm \
    /rpms/nvidia/nvidia-persistenced-5*.rpm \
    /rpms/nvidia/xorg-x11*.rpm \
    /rpms/nvidia/nvidia-container-toolkit-1*.rpm \
    /rpms/nvidia/nvidia-container-toolkit-base-1*.rpm \
    /rpms/nvidia/libnvidia-container1-1*.rpm \
    /rpms/nvidia/libnvidia-container-tools-1*.rpm

# Install dependencies and variant packages from repos
dnf5 install -y --best --allowerasing \
    libva-nvidia-driver \
    ${VARIANT_PKGS}

# Disable staging
sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/_copr_ublue-os-staging.repo

systemctl enable ublue-nvctk-cdi.service
semodule --verbose --install /usr/share/selinux/packages/nvidia-container.pp

# Universal Blue specific Initramfs fixes
cp /etc/modprobe.d/nvidia-modeset.conf /usr/lib/modprobe.d/nvidia-modeset.conf
# we must force driver load to fix black screen on boot for nvidia desktops
sed -i 's@omit_drivers@force_drivers@g' /usr/lib/dracut/dracut.conf.d/99-nvidia.conf
# as we need forced load, also mustpre-load intel/amd iGPU else chromium web browsers fail to use hardware acceleration
sed -i 's@ nvidia @ i915 amdgpu nvidia @g' /usr/lib/dracut/dracut.conf.d/99-nvidia.conf
